### ISSUE TITLE
Configuring sarif reports/ Azure Pipelines Scans

### ISSUE THREAD

**Issue by Lboer** [MarketSquare/robotframework-robocop#1113]
I have set up Robocop with Azure Pipelines for a Robot Framework repository.
I am generating a sarif report and am publishing it as a build artifact, so it shows up on the Scans tab of Azure Pipelines.

```
- script: |
    python -m robocop --reports sarif .
    python -m robocop --reports all --list-reports
  displayName: "Run Robocop Linter"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/.sarif.json'
    artifactName: CodeAnalysisLogs
  displayName: "Build Artifact"
```

This all runs without issue, however I would like to see more data in the Scans tab.
When I download the report, it includes what line the problem is on, but I don't see the lines showing up in the Scans tab.

![AzDoReport](https://github.com/user-attachments/assets/7dae13a8-15af-498a-a134-d2a229f1eb46)

I know I can write a custom script to parse over all sarif entries with a location and edit the Message.Text to get it to show up in the message.text, but is there a way to configure the report or Azure to include the location line in the Scans tab? 

Here's a sarif warning entry for context.
```
"ruleId": "0310",
"level": "warning",
"message": {
    "text": "Test, suite and global variables should be uppercase"
},
"locations": 
[
     {
        "physicalLocation": {
        "artifactLocation": {
            "uri": "RobotFrameworkApiPackage/database-keywords.resource",
            "uriBaseId": "%SRCROOT%"
        },
        "region": {
            "startLine": 113,
             "endLine": 113,
            "startColumn": 27,
            "endColumn": 38
            }
        }
    }
]
```
