### ISSUE TITLE
[Bug] Nothing is written to the output-file if it specified in a config-file.

### ISSUE THREAD

**Issue by cz-lucas** [MarketSquare/robotframework-robocop#1132]
### What happened?

Run robocop with the following pyproject.toml file:
``` toml
[tool.robocop]
reports = [
    "rules_by_id",
    "scan_timer"
]
filetypes = [".resource", ".robot"]
threshold = "I"
format = "{source}:{line}:{col} [{severity}] {rule_id} {desc} (name)"
output = "../results/robocop.log"
```
It also won't work with the example from the documentation.

### What command/code did you try to run?

`python -m robocop .` and `robocop` .`

### What is the full error message?

The file where the output should be written in is created but empty. Everything is printed to the console. If I run robocop with the `---config results/robocop.log` everything works as expected.

### What did you expect to happen instead?

The output is written to the file that is specified with the `output` in the pyproject.toml.

### Operating System

Windows 10

### Robocop version

5.5.4 and 5.5.0
